### ISSUE TITLE
DataBuilder

### ISSUE THREAD

**Issue by kevin-quach** [EpicSevenDB/gamedatabase#45] opened 2018-12-24 22:40 UTC
**Change log 1.0.1**
Dec, 24, 2018
* All % values are now automatically converted into decimal float values
* `material` category is now properly in `classType`
*  All numerical values are now converted into int and not strings
* Added missing `love` to `relationshipType`
* Added `memoryImprintFormation` to form

**Comment by kmalone86** [comment] 2018-12-30 17:47
The buff-debuff-sheet shows burn as stic_blaze, but the databuilder shows it as stic_burn. stic_burn does make more sense to me, but I have been fixing all burns to blaze in PR reviews as that is what the sheet has listed.  Either the buff-debuff-sheet.png or the databuilder should be fixed so that everything is consistant. @RaphaelDDL 


These are more requests, but would be nice as they are common mistakes and may make it faster to create a character.

Is there any chance we could get a drop down menu for stat types? For memory imprint and awakening. Have seen a few times were people put the wrong value, which is understandable because some of the values are odd, they still make sense but not to everyone.

Would it be possible to have default values in the awakening tab? Some parts of the awakening are the same for all units, mainly the additional stats. Ranks 1-3 all give 20 atk and 60 hp for every hero. Ranks 4-6 all give 30 atk and 80 hp. The resource type are almost all the same as well (3* doesn't need 2 runes types, but easy enough to just hit X after default.)
Something like this.
Rank 1:
(blank)  (blank)
atk  20
hp 60
ele-rune 0

Rank 2:
(blank)  (blank)
atk  20
hp 60
ele-rune 0
greater-ele-rune 0

Rank 3:
(blank)  (blank)
atk  20
hp 60
ele-rune 0
greater-ele-rune 0

Rank 4:
(blank)  (blank)
atk  30
hp 80
greater-ele-rune 0
epic-ele-rune 0

Rank 5:
(blank)  (blank)
atk  30
hp 80
epic-ele-rune 0
catalyst 0

Rank 6:
(blank)  (blank)
atk  30
hp 80
epic-ele-rune 0
epic-catalyst 0

**Comment by RaphaelDDL** [comment] 2018-12-30 18:55
That's a good suggestion @kmalone86 , @kevin-quach what do you think? Is it possible to let some defaults we already know?

**Comment by kevin-quach** [comment] 2018-12-30 20:30
@kmalone86 thanks for the status effect catch. I'll fix that. 

Yeah we can definitely add some more defaults to make the process's faster. If there's anymore default values other than the awakening you know about, I'll definitely add them. Haven't been following the actual data collecting conversation so I'm not aware of some of the shared similarities.

**Comment by RaphaelDDL** [comment] 2019-01-02 16:16
@kevin-quach One thing I just noticed now:

If we let int numbers be strings (let's say, `rarity` as string), it messes up mongo's sorting. My sorting is a simple `collection.find().project(/*projection to send only specific fields*/).sort({rarity: -1});`. 

Check it out: https://epicsevendb-apiserver.herokuapp.com/api/hero

Destina, Shadow Rose, Angelica and Dominiel are listed first because their rarity are strings.

I could make the script that builds into the json I import to mongo convert it, though. You think it's too troublesome to change all numbers be int (or float) instead of string? Otherwise I'll update my build script.

**Comment by kmalone86** [comment] 2019-01-02 18:17
@RaphaelDDL  I believe this was already fixed with his original changes.

"All numerical values are now converted into int and not strings"

The problem is all the heroes generated before the fix need to be re-imported and exported to pick up change. Though importing then exporting doesn't look to change percents to decimal. I did this for Judge Kise and her awakening stayed percents (chc 6% stayed instead of going to chc 0.06).

It may be worth while adding in some version fields, so we can search to see what needs to be updated in future.
clientVersion: 1.0.75 OH PV169 NV169
builderVersion: 1.0

**Comment by kmalone86** [comment] 2019-01-02 19:48
Ok, maybe I was wrong about the string to int fix affecting rarity as I just started a new one and the export is showing "5". I am guessing the import keeps the value the same as passed in, as Judge Kise stayed as int, but a new one comes up at a string rather than int.

**Comment by kevin-quach** [comment] 2019-01-02 21:33
Yeah, rarity is the only one that still ends up a string (how did I miss that one <_<). My apologies. I can fix it but I agree it would be a safe measure to include something to double check and convert it to an int just incase for future jsons.

**Comment by RaphaelDDL** [comment] 2019-01-08 22:03
Closing since it seems it was fixed.

Also for anyone coming from search, databuilder issues/PRs can be now done directly on it's repo: https://github.com/EpicSevenDB/e7-databuilder

Thank you Squachie 💃

**Closed by RaphaelDDL** 2019-01-08 22:03 UTC
Labels: enhancement
